/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Jitsi Meet",
  "tagline": "State-of-the-art video conferencing you can self-host.",
  "url": "https://rmshadows.github.io",
  "baseUrl": "/handbook/",
  "organizationName": "jitsi",
  "projectName": "handbook",
  "favicon": "img/favicon.svg",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "throw",
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "showLastUpdateAuthor": false,
          "showLastUpdateTime": true,
          "editUrl": "https://github.com/jitsi/handbook/edit/master/",
          "path": "docs",
          "sidebarPath": "/home/ryan/Project/jitsi_handbook_zhcn/sidebars.js"
        },
        "theme": {
          "customCss": [
            "/home/ryan/Project/jitsi_handbook_zhcn/src/css/custom.css"
          ]
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-client-redirects",
      {
        "redirects": [
          {
            "to": "/docs/category/user-guide",
            "from": [
              "/docs/user-guide",
              "/docs/user-guide/user-guide-start"
            ]
          },
          {
            "to": "/docs/category/developer-guide",
            "from": [
              "/docs/dev-guide",
              "/docs/dev-guide/dev-guide-start"
            ]
          },
          {
            "to": "/docs/devops-guide/",
            "from": "/docs/devops-guide/devops-guide-start"
          }
        ]
      }
    ]
  ],
  "themeConfig": {
    "prism": {
      "additionalLanguages": [
        "java",
        "markdown",
        "bash",
        "gradle",
        "lua",
        "dart"
      ],
      "lang": {
        "shell": "bash"
      },
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "algolia": {
      "appId": "K2ODL876OV",
      "apiKey": "fc233b31ee025aa87cf553bd9e7ce9e9",
      "indexName": "jitsi",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "navbar": {
      "title": "Jitsi Meet Handbook",
      "logo": {
        "src": "img/logo.svg"
      },
      "items": [
        {
          "to": "docs/intro",
          "label": "Docs - 文档",
          "position": "left"
        },
        {
          "to": "docs/category/sdks",
          "label": "SDKs",
          "position": "left"
        },
        {
          "to": "docs/releases",
          "label": "Releases - 发布",
          "position": "left"
        },
        {
          "href": "https://community.jitsi.org",
          "label": "Community - 社区",
          "position": "left"
        },
        {
          "href": "https://jaas.8x8.vc",
          "label": "JaaS",
          "position": "left"
        },
        {
          "href": "https://github.com/jitsi",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        }
      ],
      "hideOnScroll": false
    },
    "image": "img/undraw_online.svg",
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Introduction - 概述",
              "to": "docs/intro"
            },
            {
              "label": "User Guide - 用户指南",
              "to": "docs/category/user-guide"
            },
            {
              "label": "Developer Guide - 开发者指南",
              "to": "docs/category/developer-guide"
            },
            {
              "label": "Self-Hosting Guide - 自托管指南",
              "to": "docs/devops-guide"
            }
          ]
        },
        {
          "title": "Community - 社区",
          "items": [
            {
              "label": "Forum - 论坛",
              "href": "https://community.jitsi.org"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/jitsinews"
            }
          ]
        },
        {
          "title": "More - 更多",
          "items": [
            {
              "label": "Blog - 博客",
              "href": "https://jitsi.org"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/jitsi"
            },
            {
              "label": "JaaS: Jitsi as a Service",
              "href": "https://jaas.8x8.vc"
            }
          ]
        }
      ],
      "logo": {
        "alt": "8x8 Footer Logo",
        "src": "img/8x8-copyright-icon.svg",
        "href": "https://8x8.com"
      },
      "copyright": "Copyright © 8x8, Inc."
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "future": {
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
